In [1]:
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.svm import SVC, LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
data=pd.read_csv('a1_raw.csv')
print(data["phase"].value_counts())
data.head(4)

Rest           698
Stroke         656
Retraction     191
Preparation    163
Hold            39
Name: phase, dtype: int64

,lhx,lhy,lhz,rhx,rhy,rhz,hx,hy,hz,sx,sy,sz,lwx,lwy,lwz,rwx,rwy,rwz,timestamp,phase
0,5.347435,4.363681,1.501913,5.258967,4.319263,1.488703,5.037871,1.618295,1.778350,5.062803,4.229656,1.772577,4.972902,4.301065,1.564781,5.553945,4.370456,1.553521,5702026,Rest
1,4.869622,4.254210,1.556133,5.240113,4.346338,1.554309,5.037610,1.618370,1.778573,5.061430,4.228504,1.772859,4.974908,4.303656,1.565527,5.423875,4.303708,1.569942,5702058,Rest
2,5.357447,4.364039,1.500969,5.238928,4.347924,1.554150,5.037514,1.618298,1.778774,5.059245,4.228004,1.773568,4.981612,4.305363,1.563643,5.332170,4.438061,1.572841,5702089,Rest
3,4.942886,4.281878,1.546513,5.111436,4.229660,1.527091,5.037526,1.618612,1.778855,5.056475,4.226891,1.774519,4.987158,4.304063,1.565929,5.311104,4.396774,1.566368,5702120,Rest

Son kolonda 5 type class var. Multiclass olan veriyi multi binary olarak yazıyorum. Her Binary için svm çalıştırcam.

In [3]:
data=np.array(data)
new1=np.array(list(range(data.shape[0])))
new2=np.array(list(range(data.shape[0])))
new3=np.array(list(range(data.shape[0])))
new4=np.array(list(range(data.shape[0])))
new5=np.array(list(range(data.shape[0])))
for i in list(range(data.shape[0])):
    if data[i,19]=='Rest':
            new1[i]=1
    else:
            new1[i]=0
    if data[i,19]=='Stroke':
            new2[i]=1
    else:
            new2[i]=0
    if data[i,19]=='Retraction':
            new3[i]=1
    else:
            new3[i]=0
    if data[i,19]=='Preparation':
            new4[i]=1
    else:
            new4[i]=0
    if data[i,19]=='Hold':
            new5[i]=1
    else:
            new5[i]=0

In [4]:
newdata=np.column_stack([data[:,:19], new1, new2, new3, new4, new5])
pd.DataFrame(newdata).head(2)

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,5.34743,4.36368,1.50191,5.25897,4.31926,1.4887,5.03787,1.6183,1.77835,5.0628,...,1.56478,5.55394,4.37046,1.55352,5702026,1,0,0,0,0
1,4.86962,4.25421,1.55613,5.24011,4.34634,1.55431,5.03761,1.61837,1.77857,5.06143,...,1.56553,5.42387,4.30371,1.56994,5702058,1,0,0,0,0

In [29]:
X = np.array(newdata)[:,:19]
y1 = np.array(newdata)[:,19]
y2 = np.array(newdata)[:,20]
y3 = np.array(newdata)[:,21]
y4 = np.array(newdata)[:,22]
y5 = np.array(newdata)[:,23]
X_train, X_test, y1_train, y1_test, y2_train, y2_test, y3_train, y3_test, y4_train, y4_test, y5_train, y5_test = train_test_split(X, y1, y2, y3, y4, y5, test_size=0.75)

In [33]:
clf = SVC(kernel='linear')
clf.fit(X_train, y1_train)

ValueError: Unknown label type: 'unknown'